# Generated by Django 6.0.2 on 2026-03-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_salesorders_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        DO $$
                        BEGIN
                            IF to_regclass('public.inventory_salesorder') IS NOT NULL
                               AND to_regclass('public.inventory_salesorders') IS NULL THEN
                                ALTER TABLE inventory_salesorder RENAME TO inventory_salesorders;
                            END IF;
                        END $$;
                        """
                    ),
                    reverse_sql=(
                        """
                        DO $$
                        BEGIN
                            IF to_regclass('public.inventory_salesorders') IS NOT NULL
                               AND to_regclass('public.inventory_salesorder') IS NULL THEN
                                ALTER TABLE inventory_salesorders RENAME TO inventory_salesorder;
                            END IF;
                        END $$;
                        """
                    ),
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="salesorder",
                    table="inventory_salesorders",
                )
            ],
        ),
        migrations.AddField(
            model_name="salesorder",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="expected_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.salesorder",
            ),
        ),
    ]
