# Generated by Django 6.0.2 on 2026-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_salesorder_issue_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="delivery_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="quantity_delivered",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
