# Generated by Django 6.0.2 on 2026-03-02 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_salesorderitem_delivery_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="delivery_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=10
            ),
        ),
    ]
