# Generated by Django 6.0.2 on 2026-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_purchaseorderitem_delivery_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="initial_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
